- include_tasks: ppas.yml
- include_tasks: repos.yml

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Remove Amazon app package
  apt:
    name: ubuntu-web-launchers
    state: absent
