- include_tasks: ppas.yml
- include_tasks: repos.yml

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install hardware enablement stack (newer kernel and X)
  apt:
    name: [ linux-generic-hwe-18.04, xserver-xorg-hwe-18.04 ]
    state: present

- name: Install preload to reduce application load time
  apt:
    name: preload
    state: present

- name: Remove Amazon app package
  apt:
    name: ubuntu-web-launchers
    state: absent
