- name: install NodeJS
  apt:
    name: nodejs
    state: present

- name: create .npm-global directory
  file:
    path: "/home/{{ username }}/.npm-global"
    owner: "{{ username }}"
    group: "{{ group }}"
    state: directory

- name: update global package install directory and add to user's PATH
  become: yes
  become_user: "{{ username }}"
  shell: npm config set prefix "/home/{{ username }}/.npm-global/lib" && echo 'export PATH=/home/{{ username }}/.npm-global/bin:$PATH' >> /home/{{ username }}/.profile

- name: install npm
  become: yes
  become_user: "{{ username }}"
  shell: npm i -g npm

- name: install yarn
  become: yes
  become_user: "{{ username }}"
  shell: npm i -g yarn