- name: Install PostgreSQL
  apt:
    name: [ postgresql, postgresql-contrib, libpq-dev, python-psycopg2 ]
    state: present

- name: Make sure postgres is running
  service: name=postgresql state=started enabled=yes

- name: Add local user as Postgres Superuser
  become: yes
  become_user: postgres
  postgresql_user:
    name: coder
    role_attr_flags: SUPERUSER
